### ISSUE TITLE
define response message format in xsd file

### ISSUE THREAD

**Issue by fuj** [guanghao479/HoneyBadger#12]
@emmalzhang
@fuj
@Samlou

**Comment by guanghao479** [comment]
Checked in as commit 8e72d581d9d1496cc6d75d3a4fe5f1fb7aec1883, please review.

**Comment by fuj** [comment]
I saw the change. request/respond info was hard-coded in message name eventually -- I"m not against it.

Issues I saw:
1. registerRequestMesage should have an email field as well, at least;
1. in the test client, send_text_file need to be modified as well. I'll modify register and login in test client.

**Comment by guanghao479** [comment]
On Sun, Dec 18, 2011 at 6:21 PM, Jing Fu <
reply@reply.github.com
