### ISSUE TITLE
server thread non-blocking listen 

### ISSUE THREAD

**Issue by fuj** [guanghao479/HoneyBadger#2]
How does server listen thread spawn request processing thread, or even a pool of working thread?

**Comment by emmalzhang** [comment]
I'm sick. I'll see what I can do tomorrow 

Li (Emma) Zhang

Phd student
Department of Computer Science
Rensselaer Polytechnic Institute

在 Nov 21, 2011，9:34 PM，Jing Fureply@reply.github.com 写道：

**Comment by fuj** [comment]
@emmalzhang -- 

I know you are sick, I'm trying out the ticket system here with ding. Also it's pretty handy set a list of memos here to keep track of all the TODOs.
